name: eduapge2
description: A custom mobile client for EduPage, focusing on design and speed improvement
publish_to: none
version: 1.12.0
environment:
  sdk: ^3.2.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  flutter_session_manager: ^1.0.3
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  sentry_flutter: ^9.8.0
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_performance: ^0.11.1+2
  html_unescape: ^2.0.0
  flutter_cached_pdfview: ^0.4.3
  url_launcher: ^6.3.2
  shorebird_code_push: ^2.0.5
  restart_app: ^1.3.2
  flutter_linkify: ^6.0.0
  dynamic_color: ^1.8.1
  firebase_remote_config: ^6.1.1
  flutter_displaymode: ^0.7.0
  app_links: ^6.4.1
  toastification: ^3.0.3
  auto_size_text: ^3.0.0
  introduction_screen: ^4.0.0
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  assets:
    - shorebird.yaml
    - assets/EduPage2/png/logo-no-background.png
  generate: true
  uses-material-design: true
